//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class application {
    
    private string workingDirField;
    
    private string defaultAuthorityField;
    
    private string primaryAuthorityField;
    
    private string sourceSystemField;
    
    private string sourceTypeField;
    
    private string sourceDateField;
    
    private applicationWorkflow[] workflowField;
    
    private applicationCodingSystems[] codingSystemsField;
    
    private applicationSecurity[] securityField;
    
    private applicationEndpoint[] endpointField;
    
    private applicationCoverage[] coverageField;
    
    private applicationCrosswalk[] crosswalkField;
    
    private applicationDemographics[] demographicsField;
    
    private applicationDocuments[] documentsField;
    
    private applicationEncounters[] encountersField;
    
    private applicationEvents[] eventsField;
    
    private applicationProblems[] problemsField;
    
    private applicationProblemsmora[] problemsmoraField;
    
    private applicationProblemsmorb[] problemsmorbField;
    
    private applicationProblemsmorc[] problemsmorcField;
    
    private applicationProblemsraps[] problemsrapsField;
    
    private applicationProcedures[] proceduresField;
    
    private applicationProviders[] providersField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string workingDir {
        get {
            return this.workingDirField;
        }
        set {
            this.workingDirField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string defaultAuthority {
        get {
            return this.defaultAuthorityField;
        }
        set {
            this.defaultAuthorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string primaryAuthority {
        get {
            return this.primaryAuthorityField;
        }
        set {
            this.primaryAuthorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceSystem {
        get {
            return this.sourceSystemField;
        }
        set {
            this.sourceSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceDate {
        get {
            return this.sourceDateField;
        }
        set {
            this.sourceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("workflow", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationWorkflow[] workflow {
        get {
            return this.workflowField;
        }
        set {
            this.workflowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("codingSystems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationCodingSystems[] codingSystems {
        get {
            return this.codingSystemsField;
        }
        set {
            this.codingSystemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("security", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationSecurity[] security {
        get {
            return this.securityField;
        }
        set {
            this.securityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("endpoint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationEndpoint[] endpoint {
        get {
            return this.endpointField;
        }
        set {
            this.endpointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("coverage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationCoverage[] coverage {
        get {
            return this.coverageField;
        }
        set {
            this.coverageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("crosswalk", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationCrosswalk[] crosswalk {
        get {
            return this.crosswalkField;
        }
        set {
            this.crosswalkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("demographics", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationDemographics[] demographics {
        get {
            return this.demographicsField;
        }
        set {
            this.demographicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("documents", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationDocuments[] documents {
        get {
            return this.documentsField;
        }
        set {
            this.documentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("encounters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationEncounters[] encounters {
        get {
            return this.encountersField;
        }
        set {
            this.encountersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("events", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationEvents[] events {
        get {
            return this.eventsField;
        }
        set {
            this.eventsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("problems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationProblems[] problems {
        get {
            return this.problemsField;
        }
        set {
            this.problemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("problemsmora", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationProblemsmora[] problemsmora {
        get {
            return this.problemsmoraField;
        }
        set {
            this.problemsmoraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("problemsmorb", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationProblemsmorb[] problemsmorb {
        get {
            return this.problemsmorbField;
        }
        set {
            this.problemsmorbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("problemsmorc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationProblemsmorc[] problemsmorc {
        get {
            return this.problemsmorcField;
        }
        set {
            this.problemsmorcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("problemsraps", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationProblemsraps[] problemsraps {
        get {
            return this.problemsrapsField;
        }
        set {
            this.problemsrapsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("procedures", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationProcedures[] procedures {
        get {
            return this.proceduresField;
        }
        set {
            this.proceduresField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("providers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationProviders[] providers {
        get {
            return this.providersField;
        }
        set {
            this.providersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationWorkflow {
    
    private string deleteOnCloseField;
    
    private applicationWorkflowValidation[] validationField;
    
    private applicationWorkflowMap[] mapField;
    
    private applicationWorkflowReduce[] reduceField;
    
    private applicationWorkflowOutput[] outputField;
    
    private applicationWorkflowUpload[] uploadField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deleteOnClose {
        get {
            return this.deleteOnCloseField;
        }
        set {
            this.deleteOnCloseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("validation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationWorkflowValidation[] validation {
        get {
            return this.validationField;
        }
        set {
            this.validationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("map", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationWorkflowMap[] map {
        get {
            return this.mapField;
        }
        set {
            this.mapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("reduce", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationWorkflowReduce[] reduce {
        get {
            return this.reduceField;
        }
        set {
            this.reduceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("output", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationWorkflowOutput[] output {
        get {
            return this.outputField;
        }
        set {
            this.outputField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("upload", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public applicationWorkflowUpload[] upload {
        get {
            return this.uploadField;
        }
        set {
            this.uploadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationWorkflowValidation {
    
    private string enabledField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationWorkflowMap {
    
    private string enabledField;
    
    private string overwriteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string overwrite {
        get {
            return this.overwriteField;
        }
        set {
            this.overwriteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationWorkflowReduce {
    
    private string enabledField;
    
    private string overwriteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string overwrite {
        get {
            return this.overwriteField;
        }
        set {
            this.overwriteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationWorkflowOutput {
    
    private string enabledField;
    
    private string pathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationWorkflowUpload {
    
    private string enabledField;
    
    private string overwriteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string overwrite {
        get {
            return this.overwriteField;
        }
        set {
            this.overwriteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationCodingSystems {
    
    private string cPTLabelField;
    
    private string iCD9DXLabelField;
    
    private string iCD9SGLabelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CPTLabel {
        get {
            return this.cPTLabelField;
        }
        set {
            this.cPTLabelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ICD9DXLabel {
        get {
            return this.iCD9DXLabelField;
        }
        set {
            this.iCD9DXLabelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ICD9SGLabel {
        get {
            return this.iCD9SGLabelField;
        }
        set {
            this.iCD9SGLabelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationSecurity {
    
    private string keyField;
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationEndpoint {
    
    private string serverField;
    
    private string batchNameField;
    
    private string usernameField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string server {
        get {
            return this.serverField;
        }
        set {
            this.serverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string batchName {
        get {
            return this.batchNameField;
        }
        set {
            this.batchNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationCoverage {
    
    private string pathField;
    
    private string sourceSystemField;
    
    private string sourceTypeField;
    
    private string sourceDateField;
    
    private string linesToSkipField;
    
    private string editTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceSystem {
        get {
            return this.sourceSystemField;
        }
        set {
            this.sourceSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceDate {
        get {
            return this.sourceDateField;
        }
        set {
            this.sourceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string linesToSkip {
        get {
            return this.linesToSkipField;
        }
        set {
            this.linesToSkipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string editType {
        get {
            return this.editTypeField;
        }
        set {
            this.editTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationCrosswalk {
    
    private string pathField;
    
    private string sourceSystemField;
    
    private string sourceTypeField;
    
    private string sourceDateField;
    
    private string linesToSkipField;
    
    private string editTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceSystem {
        get {
            return this.sourceSystemField;
        }
        set {
            this.sourceSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceDate {
        get {
            return this.sourceDateField;
        }
        set {
            this.sourceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string linesToSkip {
        get {
            return this.linesToSkipField;
        }
        set {
            this.linesToSkipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string editType {
        get {
            return this.editTypeField;
        }
        set {
            this.editTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationDemographics {
    
    private string pathField;
    
    private string sourceSystemField;
    
    private string sourceTypeField;
    
    private string sourceDateField;
    
    private string linesToSkipField;
    
    private string editTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceSystem {
        get {
            return this.sourceSystemField;
        }
        set {
            this.sourceSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceDate {
        get {
            return this.sourceDateField;
        }
        set {
            this.sourceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string linesToSkip {
        get {
            return this.linesToSkipField;
        }
        set {
            this.linesToSkipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string editType {
        get {
            return this.editTypeField;
        }
        set {
            this.editTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationDocuments {
    
    private string pathField;
    
    private string sourceSystemField;
    
    private string sourceTypeField;
    
    private string sourceDateField;
    
    private string linesToSkipField;
    
    private string editTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceSystem {
        get {
            return this.sourceSystemField;
        }
        set {
            this.sourceSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceDate {
        get {
            return this.sourceDateField;
        }
        set {
            this.sourceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string linesToSkip {
        get {
            return this.linesToSkipField;
        }
        set {
            this.linesToSkipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string editType {
        get {
            return this.editTypeField;
        }
        set {
            this.editTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationEncounters {
    
    private string pathField;
    
    private string sourceSystemField;
    
    private string sourceTypeField;
    
    private string sourceDateField;
    
    private string linesToSkipField;
    
    private string editTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceSystem {
        get {
            return this.sourceSystemField;
        }
        set {
            this.sourceSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceDate {
        get {
            return this.sourceDateField;
        }
        set {
            this.sourceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string linesToSkip {
        get {
            return this.linesToSkipField;
        }
        set {
            this.linesToSkipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string editType {
        get {
            return this.editTypeField;
        }
        set {
            this.editTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationEvents {
    
    private string pathField;
    
    private string sourceSystemField;
    
    private string sourceTypeField;
    
    private string sourceDateField;
    
    private string linesToSkipField;
    
    private string editTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceSystem {
        get {
            return this.sourceSystemField;
        }
        set {
            this.sourceSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceDate {
        get {
            return this.sourceDateField;
        }
        set {
            this.sourceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string linesToSkip {
        get {
            return this.linesToSkipField;
        }
        set {
            this.linesToSkipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string editType {
        get {
            return this.editTypeField;
        }
        set {
            this.editTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationProblems {
    
    private string pathField;
    
    private string sourceSystemField;
    
    private string sourceTypeField;
    
    private string sourceDateField;
    
    private string linesToSkipField;
    
    private string editTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceSystem {
        get {
            return this.sourceSystemField;
        }
        set {
            this.sourceSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceDate {
        get {
            return this.sourceDateField;
        }
        set {
            this.sourceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string linesToSkip {
        get {
            return this.linesToSkipField;
        }
        set {
            this.linesToSkipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string editType {
        get {
            return this.editTypeField;
        }
        set {
            this.editTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationProblemsmora {
    
    private string pathField;
    
    private string sourceSystemField;
    
    private string sourceTypeField;
    
    private string sourceDateField;
    
    private string linesToSkipField;
    
    private string editTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceSystem {
        get {
            return this.sourceSystemField;
        }
        set {
            this.sourceSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceDate {
        get {
            return this.sourceDateField;
        }
        set {
            this.sourceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string linesToSkip {
        get {
            return this.linesToSkipField;
        }
        set {
            this.linesToSkipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string editType {
        get {
            return this.editTypeField;
        }
        set {
            this.editTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationProblemsmorb {
    
    private string pathField;
    
    private string sourceSystemField;
    
    private string sourceTypeField;
    
    private string sourceDateField;
    
    private string linesToSkipField;
    
    private string editTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceSystem {
        get {
            return this.sourceSystemField;
        }
        set {
            this.sourceSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceDate {
        get {
            return this.sourceDateField;
        }
        set {
            this.sourceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string linesToSkip {
        get {
            return this.linesToSkipField;
        }
        set {
            this.linesToSkipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string editType {
        get {
            return this.editTypeField;
        }
        set {
            this.editTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationProblemsmorc {
    
    private string pathField;
    
    private string sourceSystemField;
    
    private string sourceTypeField;
    
    private string sourceDateField;
    
    private string linesToSkipField;
    
    private string editTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceSystem {
        get {
            return this.sourceSystemField;
        }
        set {
            this.sourceSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceDate {
        get {
            return this.sourceDateField;
        }
        set {
            this.sourceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string linesToSkip {
        get {
            return this.linesToSkipField;
        }
        set {
            this.linesToSkipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string editType {
        get {
            return this.editTypeField;
        }
        set {
            this.editTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationProblemsraps {
    
    private string pathField;
    
    private string sourceSystemField;
    
    private string sourceTypeField;
    
    private string sourceDateField;
    
    private string linesToSkipField;
    
    private string editTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceSystem {
        get {
            return this.sourceSystemField;
        }
        set {
            this.sourceSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceDate {
        get {
            return this.sourceDateField;
        }
        set {
            this.sourceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string linesToSkip {
        get {
            return this.linesToSkipField;
        }
        set {
            this.linesToSkipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string editType {
        get {
            return this.editTypeField;
        }
        set {
            this.editTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationProcedures {
    
    private string pathField;
    
    private string sourceSystemField;
    
    private string sourceTypeField;
    
    private string sourceDateField;
    
    private string linesToSkipField;
    
    private string editTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceSystem {
        get {
            return this.sourceSystemField;
        }
        set {
            this.sourceSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceDate {
        get {
            return this.sourceDateField;
        }
        set {
            this.sourceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string linesToSkip {
        get {
            return this.linesToSkipField;
        }
        set {
            this.linesToSkipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string editType {
        get {
            return this.editTypeField;
        }
        set {
            this.editTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class applicationProviders {
    
    private string pathField;
    
    private string sourceSystemField;
    
    private string sourceTypeField;
    
    private string sourceDateField;
    
    private string linesToSkipField;
    
    private string editTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceSystem {
        get {
            return this.sourceSystemField;
        }
        set {
            this.sourceSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceDate {
        get {
            return this.sourceDateField;
        }
        set {
            this.sourceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string linesToSkip {
        get {
            return this.linesToSkipField;
        }
        set {
            this.linesToSkipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string editType {
        get {
            return this.editTypeField;
        }
        set {
            this.editTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private application[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("application")]
    public application[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
